import type { NextPage } from "next";
import Head from "next/head";
import Tree from "components/Tree";
import styles from "styles/Home.module.css";

import lists from "json/tree.json";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tree List Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <footer className={styles.footer}>
        <span style={{ display: "flex", alignItems: "center" }}>
          Made with ❤️ by&nbsp;
          <a
            href="https://www.instagram.com/fjri.p"
            target="_blank"
            rel="noopener noreferrer"
            style={{ textTransform: "capitalize" }}
          >
            fajri
          </a>
        </span>
      </footer>

      <main className={styles.main}>
        <Tree lists={lists} />
      </main>
    </div>
  );
};

export default Home;
